version: '3.8'
services:
  note-delivery:
    build:
      context: .
    image: note-delivery:1.0.0
    ports:
    - published: 4200
      target: 4200
    user: '100000'
    volumes:
    - ./config.json:/app/config.json:ro
